# Generated by Django 5.1.3 on 2024-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_project_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee_role',
            field=models.CharField(choices=[('QC', 'QualityAssurace'), ('FD', 'FrontEndDev'), ('BD', 'BackEndDev'), ('TT', 'Tester')], max_length=255),
        ),
    ]
